import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/react";

export const metadata: Metadata = {
  title: "Aneztech",
  description:
    "Generated by create next app, bikin website, jasa bikin website, nezt, aneztech, nez.t",
  keywords:
    "website, webdev, web, developer, nezt, aneztech, nez.t, webdeveloper, bikinwebsite, bikin web, bikin website, nextjs, nextjs website, nextjs web, nextjs developer"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
